language: bash
before_install:
- sudo apt-get update
install:
- sudo apt-get install -y qemu qemu-user-static binfmt-support debootstrap debian-ports-archive-keyring
  --no-install-recommends
script:
- sudo BUILD_ARCH=armhf ./build.sh
- sudo BUILD_ARCH=arm64 ./build.sh
- ls -al rootfs-*.tar.gz
deploy:
  provider: releases
  file:
  - rootfs-armhf.tar.gz
  - rootfs-arm64.tar.gz
  skip_cleanup: true
  on:
    tags: true
    repo: DieterReuter/make-roofs-debian-arm64
  api-key:
    secure: vb0KUiIPXOW2zJreFLbpVCsETs3q/+W7NPZSN237Ar1c3zuEBmW+57b/QaYvBeJeGNbv62N61/gjgTa5jL8n/3PlcHFAEgFvPbkGiRusYc2j6uSCUc6pZPFW3VzhQ74IFl7Hy6M8L/Th88Edjbq0q+w1L/MyqhUPxCGmG+/daosecPy0CttmLyF5iLMllPB/XZvH1BIq2w4DCp2DnwSvtm/unD1WfrrQLGQWqt1f0l3Lt5gQ7XxdBm67f4hp82oajxGSmAGupDzVUlAIbt8YORdZzOeKftTsIU0dQmOYYsskzmz7GTgjVzh87u0v4M96bvAMGlwZanEifUvBQ/T2TAHCZg6JQEWVaDNJF+YQHBatnjqWGT2j839IIart7bi4CZPoKj/SEaSf7DDzO1ArdV0HmlcB783QSFx3D+VkNHAUXAztbPKzPi5Fgx+nnUNm4Mo/DEFPAhL4shziUE6qG8WjTNw0LkDLNFpYK+oicqc9x9hkQ+ZcUIJ4vufSrrtjvoSSFIFr5AzA3iwTYsvA+g/6Cu0C4bPucl+jn8YI5VSAMliSasoCkUCjnSV1Hi+KwvkbLzP4KcEQ+m/7L1nG4Vs7ZokoZQhgZiCzUiATXtzpV41EStsj+rEiOvWBmifEe2MYI7xBHWcrt75As9HNUBgEN5rJ4ayqvEzTeZ4B9Fo=
